Repository ecmwf-ifs/ectrans, pull requests merged in 2025-06, with the labels that each got.

#274 Fix GP norms in LAM (for 50T1)
  src/etrans/cpu/external/egpnorm_trans.F90
  src/trans/cpu/external/gpnorm_trans.F90
Labels: approved-for-ci, contributor

#277 Improved portability
  pyproject.toml
  setup.py
  src/ectrans4py/__init__.py
  src/ectrans4py/ectrans_version.F90
  src/ectrans4py/gp2sp_gauss4py.F90
  src/ectrans4py/gp2sp_lam4py.F90
  src/ectrans4py/sp2gp_gauss4py.F90
  src/ectrans4py/sp2gp_lam4py.F90
Labels: contributor

#264 Add LAM capability to transi via etrans
  cmake/ectrans-import.cmake.in
  src/etrans/cpu/internal/eftinv_ctlad_mod.F90
  src/trans/common/external/setup_trans0.F90
  src/transi/CMakeLists.txt
  src/transi/transi.c
  src/transi/transi.h
  src/transi/transi_module.F90
  tests/CMakeLists.txt
  tests/transi/transi_test.c
  tests/transi/transi_test.h
  tests/transi/transi_test_lam.c
  tests/transi/transi_test_lam_dirtrans_adjoint.c
  tests/transi/transi_test_lam_invtrans_adjoint.c
Labels: approved-for-ci
