Repository ecmwf-ifs/ectrans, pull requests merged in 2025-03, with the labels that each got.

#221 Add two forgotten renames for ETRANS.
  src/etrans/sedrenames.txt
Labels: contributor

#210 Remove _OVERLOAD layer
  src/trans/gpu/algor/hicblas_mod.F90
  src/trans/gpu/internal/ledir_mod.F90
  src/trans/gpu/internal/leinv_mod.F90
Labels: enhancement, gpu, contributor

#196 Permit INV_TRANS with OpenMP offload
  src/trans/gpu/algor/buffered_allocator_mod.F90
  src/trans/gpu/algor/ext_acc.F90
  src/trans/gpu/algor/hicblas_gemm.hip.cpp
  src/trans/gpu/external/setup_trans.F90
  src/trans/gpu/internal/fsc_mod.F90
  src/trans/gpu/internal/ftinv_mod.F90
  src/trans/gpu/internal/ledir_mod.F90
  src/trans/gpu/internal/leinv_mod.F90
  src/trans/gpu/internal/prfi1b_mod.F90
  src/trans/gpu/internal/spnsde_mod.F90
  src/trans/gpu/internal/tpm_hicfft.F90
  src/trans/gpu/internal/trltog_mod.F90
  src/trans/gpu/internal/trmtol_mod.F90
  src/trans/gpu/internal/trmtol_pack_unpack.F90
  src/trans/gpu/internal/vdtuv_mod.F90
Labels: enhancement, gpu

#233 Fix some formats in ectrans-benchmark.F90
  src/programs/ectrans-benchmark.F90
Labels: bug, contributor

#231 Make LUMI account a secret
  .github/workflows/build-hpc.yml
Labels: actions

#230 Always call GSTATS in GSTATS_NVTX
  src/trans/gpu/internal/tpm_stats.F90
Labels: bug, gpu

#237 Fix poa1 bug
  src/trans/cpu/internal/ledir_mod.F90
Labels: bug

#224 Update Github runners to Ubuntu 24.04
  .github/tools/install-mpi.sh
  .github/tools/install-nvhpc.sh
  .github/workflows/build.yml
Labels: actions

#234 AMD Flang support
  src/trans/gpu/algor/buffered_allocator_mod.F90
  src/trans/gpu/algor/ext_acc.F90
Labels: enhancement, gpu, approved-for-ci, contributor
