Repository ecmwf-ifs/ectrans, pull requests merged in 2025-04, with the labels that each got.

#247 amdflang support
  src/trans/gpu/internal/trltom_mod.F90
  src/trans/gpu/internal/trmtol_mod.F90
Labels: approved-for-ci, contributor

#249 MPI-free testing
  CMakeLists.txt
  tests/CMakeLists.txt
Labels: tidying

#222 Fix argument checks
  src/trans/cpu/external/dir_trans.F90
  src/trans/cpu/external/dist_grid.F90
  src/trans/cpu/external/gath_grid.F90
  src/trans/cpu/external/inv_trans.F90
  src/trans/gpu/external/dir_trans.F90
  src/trans/gpu/external/dist_grid.F90
  src/trans/gpu/external/gath_grid.F90
  src/trans/gpu/external/inv_trans.F90
Labels: tidying

#255 Fix failing ectrans4py tests
  src/ectrans4py/sp2gp_gauss4py.F90
  tests/test_ectrans4py/test_ectrans4py.py
Labels: bug, actions, ectrans4py
